backend:
  name: git-gateway
  branch: main

media_folder: "images/blog"
public_folder: "/images/blog"

collections:
  - name: "posts"
    label: "Blog Posts"
    label_singular: "Blog Post"
    folder: "posts"
    create: true
    delete: true
    slug: "{{slug}}"
    identifier_field: title
    summary: "{{title}} -- {{date}}"
    sortable_fields: ["date", "title"]
    fields:
      - { label: "Title",       name: "title",      widget: "string" }
      - { label: "Date",        name: "date",        widget: "datetime", format: "YYYY-MM-DD", date_format: "YYYY-MM-DD", time_format: false }
      - { label: "Author",      name: "author",      widget: "string",   default: "Bhargava Pejakala Kakrannaya" }
      - { label: "Emoji",       name: "emoji",       widget: "string",   default: "📝" }
      - { label: "Tags",        name: "tags",        widget: "list" }
      - { label: "Excerpt",     name: "excerpt",     widget: "text" }
      - { label: "Cover Image", name: "coverImage",  widget: "image",    required: false }
      - { label: "Body",        name: "body",        widget: "markdown" }
